### PR TITLE
Add a method to change the LayoutManager at runtime

### PR DESCRIPTION
**Pull request by Beni84**
Add a method to change the LayoutManager when the user wants to

### CODE REVIEW

**Comment by cmc00022** [comment]
@Beni84 are you sure that just changing the LayoutManager are runtime will actually works? I haven't test it, did you?

**Comment by Beni84** [comment]
Yeah, I test this new code into your sample code, I changed when the user clicks in a item of the list and only changing the layout manager, the list changed. The same thing happened in my code. This code example wasn't merged and it isn't in the pull request.

But, you can wait for testing this code, because probably I will have to add more methods in your library.

**Comment by cmc00022** [comment]
That's fine. Anyway don't know why I can see that you added two 

* Added new method to add a generic loading view (This one was already merged when you created the pull request

Please create a pull request including only the commit to change the LayoutManager at runtime.

If you want to add more features, that's fine, but create a new pull request for each of the features :)

Waiting for them, I'll merge them ASAP

**Comment by cmc00022** [comment]
Close PR. Create a new one that contains only the related commit.

**Pull request closed without merging**
