### PR TITLE
I've changed minSdkVersion for 11 and created single choice mode

### PR DESCRIPTION
**Pull request by tonilopezmr**
#7 
minSdkVersion for 11 because is the minSdkVersion of recycler animator library.

### CODE REVIEW

**Comment by tonilopezmr** [comment]
Also I've created a single choice mode, sometimes it is necessary not to allow multiple touch events.

For example in the library [Clean-Contacts](https://github.com/PaNaVTEC/Clean-Contacts) if you running in Llolipop and select multiple touch events at the same time, happen this (This happens sometimes):

      07-14 21:05:05.151  20240-20240/me.panavtec.cleancontacts E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: me.panavtec.cleancontacts, PID: 20240
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.Window.getSharedElementsUseOverlay()' on a null object reference
            at android.app.ActivityTransitionCoordinator.moveSharedElementsToOverlay(ActivityTransitionCoordinator.java:707)
            at android.app.EnterTransitionCoordinator.viewsReady(EnterTransitionCoordinator.java:126)
            at android.app.EnterTransitionCoordinator$2.onPreDraw(EnterTransitionCoordinator.java:148)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:895)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2153)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

For this, sometimes it is necessary use single choice mode.

**Comment by tonilopezmr** [comment]
Yes sorry, I meant that is multi touch and call at the same time  different listeners. If you touch at the same time with 3 different fingers, you will see 3 different calls.

**Comment by cmc00022** [comment]
Yep, what I meant is that the behaviour should be as follows. The first item that get the touch event is the one that fires the click listener, if more fingers touch other items, they won't fire any other click listeners

**Comment by tonilopezmr** [comment]
Exactly and that is what makes the commit, but the item views are selected anyway :(

**Comment by cmc00022** [comment]
I've found a way to fix that I'll add it to the repo ASAP. 

Thanks for the PR and comments. 

I'll not close it tough till the fix is added.

**Comment by cmc00022** [comment]
This has been addressed using a DebouncedListener and handlers that block multiple click listeners at once. Only the very first click will be dispatched.

**Pull request closed without merging**
